### ISSUE TITLE
currency error

### ISSUE THREAD

**Issue by ouovouo** [holodata/vtuber-livechat-dataset#3]
currency.py
![image](https://user-images.githubusercontent.com/23149851/123507426-d662b480-d69b-11eb-8dfa-f56b19bf8344.png)

![image](https://user-images.githubusercontent.com/23149851/123507404-ac10f700-d69b-11eb-951a-19cb567b615b.png)

**Comment by uetchy** [comment]
That's blatantly wrong! Thank you for letting me know about this.

**Comment by uetchy** [comment]
It will be fixed in the next build, releasing after 7/1 UTC.

**Comment by uetchy** [comment]
Instead of managing currency rates manually, we should get currency rates from an external API, but I haven't find a good API that is free to use and has good coverage.

**Comment by uetchy** [comment]
Turned out that [this API](https://rapidapi.com/fyhao/api/currency-exchange/) is good enough to cover all currencies appeared in super chats, now in postprocess it will read exchange rate from a local snapshot and only get it from the API if it is not found.

https://github.com/holodata/vtuber-livechat-dataset/blob/master/vtlc/util/currency.py
